CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    f_name VARCHAR(20) NOT NULL,
    l_name VARCHAR(20) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(20) NOT NULL UNIQUE,
    phone_number VARCHAR(13) NOT NULL UNIQUE,
    timestamp TIMESTAMPTZ NOT NULL
);